# Generated by Django 3.2.9 on 2021-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.IntegerField(max_length=5000)),
                ('description', models.TextField(max_length=500)),
                ('topspeed', models.IntegerField(max_length=500)),
            ],
        ),
    ]
