# Generated by Django 3.2.9 on 2021-11-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('s', 'Street'), ('o', 'Offroad'), ('t', 'Track')], default='s', max_length=1),
        ),
    ]
