# Generated by Django 3.2.9 on 2021-11-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='topspeed',
            field=models.IntegerField(),
        ),
    ]
