# Generated by Django 3.2.9 on 2021-11-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211124_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='topspeed',
        ),
    ]
