# Generated by Django 3.2.9 on 2021-11-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('Street', 'Street'), ('o', 'Offroad'), ('t', 'Track')], default='Street', max_length=150),
        ),
    ]
